site_name: API Documentation

nav:
  - Home: index.md
  - API: api.md

plugins:
  - search
  - neoteroi.mkdocsoad

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
